options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TAG_SUFFIX: '${SHORT_SHA}-${BUILD_ID}'  # Unique tag to avoid immutability issues

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east1-docker.pkg.dev/nse-gcp-ema-tt-37ab4-sbx-1/standup-bot/standup-bot:${_TAG_SUFFIX}',
        '-f',
        'dockerfile',
        '.'
      ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/nse-gcp-ema-tt-37ab4-sbx-1/standup-bot/standup-bot:${_TAG_SUFFIX}'
      ]

  # Step 3: Deploy to Cloud Run on port 8501
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'standup-bot',                              # Cloud Run service name
        '--image', 'us-east1-docker.pkg.dev/nse-gcp-ema-tt-37ab4-sbx-1/standup-bot/standup-bot:${_TAG_SUFFIX}',
        '--region', 'us-central1',                                  # Cloud Run region
        '--platform', 'managed',                                    # Fully managed Cloud Run
        '--allow-unauthenticated',                                  # Public access
        '--port', '8501',                                           # Cloud Run will listen on this port
        '--memory', '4Gi',                                          # Set memory to 4 GiB
        '--cpu', '4',                                               # Set CPU to 4 vCPU
        '--vpc-connector', 'standup-connector',                     # attach to VPC
        #'--vpc-egress', 'all-traffic',                         # send all traffic through the VPC
        '--service-account', 'standup-bot-sa@nse-gcp-ema-tt-37ab4-sbx-1.iam.gserviceaccount.com'
      ]

# Register the image in Cloud Build metadata
images:
  - 'us-east1-docker.pkg.dev/nse-gcp-ema-tt-37ab4-sbx-1/standup-bot/standup-bot:${_TAG_SUFFIX}'
