[server]
headless = true
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#4f46e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"
