[server]
headless = true
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"  # Or "dark"
primaryColor="#FF4B4B" # Your primary branding color (optional, affects some elements)
secondaryBackgroundColor="#F0F8FF" # Your desired background color (AliceBlue in this example)
textColor="#262730" # Default text color (optional)
font="sans serif" # Default font (optional)
